// packages/vue/src/Flowchart.vue
<template>
  <div ref="containerRef" :class="props.class" :style="containerStyle" />
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted, watch, computed, shallowRef } from 'vue'
import { FlowChart, generateId } from '@flowgl/core'
import type {
  NodeData,
  EdgeData,
  ViewportState,
  GridConfig,
  MinimapConfig,
  HandleSide,
  FlowChartOptions,
} from '@flowgl/core'

export interface ConnectParams {
  sourceId:     string
  targetId:     string
  sourceHandle: HandleSide
  targetHandle: HandleSide
}

const props = withDefaults(defineProps<{
  nodes?:            NodeData[]
  edges?:            EdgeData[]
  background?:       string
  minimap?:          Partial<MinimapConfig>
  grid?:             Partial<GridConfig>
  labelEditable?:    boolean
  readOnly?:         boolean
  historyLimit?:     number
  ariaLabel?:        string
  class?:            string
  style?:            string | Record<string, string>
  width?:            string
  height?:           string
}>(), {
  nodes:         () => [],
  edges:         () => [],
  width:         '100%',
  height:        '100%',
})

const emit = defineEmits<{
  nodesChange:    [nodes: NodeData[]]
  edgesChange:    [edges: EdgeData[]]
  connect:        [params: ConnectParams]
  nodeClick:      [node: NodeData]
  selectionChange:[params: { selectedIds: string[]; edgeIds: string[] }]
  viewportChange: [state: ViewportState]
  init:           [chart: FlowChart]
  error:          [err: Error]
}>()

const containerRef = shallowRef<HTMLDivElement | null>(null)
const chartRef     = shallowRef<FlowChart | null>(null)

// Expose chart instance via defineExpose
defineExpose({ chart: chartRef })

const containerStyle = computed(() => ({
  position: 'relative' as const,
  width:    props.width,
  height:   props.height,
  ...(typeof props.style === 'object' ? props.style : {}),
}))

// Track last-applied values to avoid echoing internal mutations back
let lastNodes: NodeData[] | undefined
let lastEdges: EdgeData[] | undefined

onMounted(() => {
  if (!containerRef.value) return

  const options: FlowChartOptions = {
    container: containerRef.value,
    nodes:     props.nodes,
    edges:     props.edges,
  }
  if (props.background   !== undefined) options.background   = props.background
  if (props.minimap      !== undefined) options.minimap      = props.minimap
  if (props.grid         !== undefined) options.grid         = props.grid
  if (props.labelEditable !== undefined) options.labelEditable = props.labelEditable
  if (props.readOnly     !== undefined) options.readOnly     = props.readOnly
  if (props.historyLimit !== undefined) options.historyLimit = props.historyLimit
  if (props.ariaLabel    !== undefined) options.ariaLabel    = props.ariaLabel
  options.onError = (err) => emit('error', err)

  const chart = new FlowChart(options)
  lastNodes = props.nodes
  lastEdges = props.edges

  chart.on('nodeDragEnd', () => {
    const nodes = chart.graph.getNodes()
    lastNodes = nodes
    emit('nodesChange', nodes)
  })

  chart.on('connect', ({ sourceId, targetId, sourceHandle, targetHandle }) => {
    chart.addEdge({ id: generateId('e'), source: sourceId, target: targetId, sourceHandle, targetHandle })
    const edges = chart.graph.getEdges()
    lastEdges = edges
    emit('edgesChange', edges)
    emit('connect', { sourceId, targetId, sourceHandle, targetHandle })
  })

  chart.on('nodeClick',       ({ node }) => emit('nodeClick', node))
  chart.on('selectionChange', (params)  => emit('selectionChange', params))
  chart.on('viewportChange',  (state)   => emit('viewportChange', state))

  chartRef.value = chart
  emit('init', chart)
})

onUnmounted(() => {
  chartRef.value?.dispose()
  chartRef.value = null
})

watch(() => props.nodes, (nodes) => {
  const chart = chartRef.value
  if (!chart || nodes === lastNodes) return
  chart.setNodes(nodes ?? [])
  lastNodes = nodes
})

watch(() => props.edges, (edges) => {
  const chart = chartRef.value
  if (!chart || edges === lastEdges) return
  chart.setEdges(edges ?? [])
  lastEdges = edges
})

watch(() => props.readOnly, (v) => {
  if (v !== undefined) chartRef.value?.setReadOnly(v)
})
</script>

// packages/svelte/src/Flowchart.svelte
<script lang="ts">
  import { onMount, onDestroy, createEventDispatcher } from 'svelte'
  import { FlowChart, generateId } from '@flowgl/core'
  import type {
    NodeData,
    EdgeData,
    ViewportState,
    GridConfig,
    MinimapConfig,
    HandleSide,
    FlowChartOptions,
  } from '@flowgl/core'

  export interface ConnectParams {
    sourceId:     string
    targetId:     string
    sourceHandle: HandleSide
    targetHandle: HandleSide
  }

  // Props
  export let nodes:         NodeData[]             = []
  export let edges:         EdgeData[]             = []
  export let background:    string | undefined     = undefined
  export let minimap:       Partial<MinimapConfig> | undefined = undefined
  export let grid:          Partial<GridConfig>    | undefined = undefined
  export let labelEditable: boolean | undefined    = undefined
  export let readOnly:      boolean | undefined    = undefined
  export let historyLimit:  number  | undefined    = undefined
  export let ariaLabel:     string  | undefined    = undefined
  export let width:         string                 = '100%'
  export let height:        string                 = '100%'
  export let className:     string                 = ''

  // Expose chart instance
  export let chart: FlowChart | null = null

  const dispatch = createEventDispatcher<{
    nodesChange:    NodeData[]
    edgesChange:    EdgeData[]
    connect:        ConnectParams
    nodeClick:      NodeData
    selectionChange:{ selectedIds: string[]; edgeIds: string[] }
    viewportChange: ViewportState
    init:           FlowChart
    error:          Error
  }>()

  let container: HTMLDivElement
  let lastNodes: NodeData[] | undefined
  let lastEdges: EdgeData[] | undefined

  onMount(() => {
    const options: FlowChartOptions = { container, nodes, edges }
    if (background    !== undefined) options.background    = background
    if (minimap       !== undefined) options.minimap       = minimap
    if (grid          !== undefined) options.grid          = grid
    if (labelEditable !== undefined) options.labelEditable = labelEditable
    if (readOnly      !== undefined) options.readOnly      = readOnly
    if (historyLimit  !== undefined) options.historyLimit  = historyLimit
    if (ariaLabel     !== undefined) options.ariaLabel     = ariaLabel
    options.onError = (err) => dispatch('error', err)

    chart = new FlowChart(options)
    lastNodes = nodes
    lastEdges = edges

    chart.on('nodeDragEnd', () => {
      const n = chart!.graph.getNodes()
      lastNodes = n
      dispatch('nodesChange', n)
    })

    chart.on('connect', ({ sourceId, targetId, sourceHandle, targetHandle }) => {
      chart!.addEdge({ id: generateId('e'), source: sourceId, target: targetId, sourceHandle, targetHandle })
      const e = chart!.graph.getEdges()
      lastEdges = e
      dispatch('edgesChange', e)
      dispatch('connect', { sourceId, targetId, sourceHandle, targetHandle })
    })

    chart.on('nodeClick',       ({ node }) => dispatch('nodeClick', node))
    chart.on('selectionChange', (params)  => dispatch('selectionChange', params))
    chart.on('viewportChange',  (state)   => dispatch('viewportChange', state))

    dispatch('init', chart)
  })

  onDestroy(() => {
    chart?.dispose()
    chart = null
  })

  // Reactive sync
  $: if (chart && nodes !== lastNodes) {
    chart.setNodes(nodes)
    lastNodes = nodes
  }

  $: if (chart && edges !== lastEdges) {
    chart.setEdges(edges)
    lastEdges = edges
  }

  $: if (chart && readOnly !== undefined) {
    chart.setReadOnly(readOnly)
  }
</script>

<div
  bind:this={container}
  class={className}
  style="position:relative;width:{width};height:{height};"
/>
